import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
   
    {
      type: 'category',
      label: 'Module 1 — The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'robotics/ros2-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2 — The Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin-sim-module/chapter-1',
        'digital-twin-sim-module/chapter-2',
        'digital-twin-sim-module/chapter-3',
        'digital-twin-sim-module/chapter-4',
        'digital-twin-sim-module/chapter-5',
      ],
    },

     {
      type: 'category',
      label: 'Module 3 — NVIDIA Isaac AI-Robot Brain',
      items: [
        'nvidia-isaac-ai-module/chapter-1',
        'nvidia-isaac-ai-module/chapter-2',
        'nvidia-isaac-ai-module/chapter-3',
        'nvidia-isaac-ai-module/chapter-4',
        'nvidia-isaac-ai-module/chapter-5',
      ],
    },
    {
      type: 'category',
      label: 'Module 4 — Vision-Language-Action (VLA)',
      items: [
        'vla-humanoid-ai-module/chapter-1',
        'vla-humanoid-ai-module/chapter-2',
        'vla-humanoid-ai-module/chapter-3',
        'vla-humanoid-ai-module/chapter-4',
        'vla-humanoid-ai-module/chapter-5',
      ],
    },
  ],
};

export default sidebars;